### PR TITLE
Multiple updates and fixes to DOCS and README

### PR DESCRIPTION
**Pull request by ravkr**
* Sort api functions alphabetically
* Add example how to use Github version (a.k.a _Bleeding Edge_) of facebook-chat-api instead of NPM version (_stable_)
* Change examples to use _appState_ instead of _email_+_password_ login
  (it is easier to use, you only have to login once and you don't have to put your password in every source file…)
* Add
  ```js
  const fs = require("fs");
  const login = require("facebook-chat-api");
  ```
  to examples where it was missing
* Some blocks of code were using 2 spaces as indentation - changed to 4 spaces, to match the rest
* change callbacks in examples from these inconsistent forms:
  * `function callback(err, api){}`
  * `function callback (err, api) {}`
  * `function(err, api) {}`
  * `function (err, api) {}`
  (and few other)
  to a single, simpler form:
  * `(err, api) => {}`.
* change `(…, [callback])` to `(…[, callback])`
* many other little fixes. (e.g. `callback(err)` where it should be `console.error(err)`)

### CODE REVIEW

**Comment by Schmavery** [comment]
Wow thanks for this work @ravkr !  The api really needed a docs overhaul.
The only thing I'm a little reluctant about is the change to using appstate everywhere rather than email+password.  I think the latter is much easier for people to understand/quickly try out.  Otherwise people will first need to know how to generate an appstate (which is not super trivial).  

I definitely don't suggest putting your passwords in source files however.. when we use the api we load a config file with login info or grab it from environment variables.  I had assumed other people would do things like this as well, but I've seen a number of repos on github using our api make this same mistake so maybe I'm wrong.  What do you think about a section near the top of the README talking about password safety or something?  Maybe as an extension to the section about appState.  I'm not sure.

**Comment by Schmavery** [comment]
Sorry about causing conflicts in this.  I'd love to have the pretty new clean docs before publishing the newest version to npm :smile:

**Comment by Schmavery** [comment]
As soon as you can fix this I'll publish 1.3.1 to npm with the new docs 😄

**Comment by ravkr** [comment]
Done :smiley:

**Comment by Schmavery** [comment]
Thanks for doing this so fast!  I'll merge and maybe tweak a couple words when I get a minute, and then your changes will be published for all the world to see :)

**Comment by ravkr** [comment]
I hope that I didn't make many errors :unamused: english is not my native language

**Comment by Schmavery** [comment]
Thanks again @ravkr ! :smile:

**Pull request merged**
