### PR TITLE
Correct errors in documentation

### PR DESCRIPTION
**Pull request by Weetbix**
Fixes a few errors in the API documentation

### CODE REVIEW

**Comment by Schmavery** [comment]
Thanks for catching these.
In the changeArchiveStatus docs, can you change all mentions of "state" to the use the word "status"?

On line 126, can you make it say "The id(s) of the threads you wish to archive/unarchive."
On 127, please specify that the value should be a boolean.

If you could add a short example, that would also be awesome.

**Comment by Weetbix** [comment]
No problem, should be good now. I also added a description of what archiving is.

This is a great project, so thanks for all your work and merry christmas! :santa:

**Comment by Schmavery** [comment]
I would maybe change your thread ID to 0000000000000 to stay consistent with the other examples.  Other than that looks awesome and I'm always happy to merge doc fixes :D

**Comment by Weetbix** [comment]
Done :+1:

**Comment by Schmavery** [comment]
Weird, thought I already merged this.  Thanks again.

**Pull request merged**
