### PR TITLE
Fix: Avoid bad rendering of README on npm

### PR DESCRIPTION
**Pull request by cadesalaberry**
Sorry, the last commit did not go through completely.

I tested it with `marky-markdown`, the problem was that the `a` tag  was not closed.

I closed it and moved it after the title.

For clarification, I was talking about the html rendering of the `README.md` file on [npm](https://github.com/Schmavery/facebook-chat-api)

### CODE REVIEW

**Comment by Schmavery** [comment]
Huh well.. the `a` tag was closed... I guess npm's parser sucks.

**Comment by bsansouci** [comment]
O_O
Can you file an issue on https://github.com/npm/marky-markdown to tell them they probably should support more than a subset of HTML

**Comment by Schmavery** [comment]
http://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5
I guess you can't self-close an anchor tag... pretty lame.

**Comment by Schmavery** [comment]
It looks like the header auto-creates an anchor tag.  Can we link to #projects-using-this-api instead and remove the `<a name="projects" />` instead?

**Comment by cadesalaberry** [comment]
@bsansouci  Yep, that's what I realised about anchor tags too...

@Schmavery That's what I wanted to do, but I realised you could have used the link somewhere else apart from github.

I figured it would be better to keep it that way.

However if the `README.md` is the sole place the **#projects** is used, yes it can be referenced with **#projects-using-this-api**.

**Comment by Schmavery** [comment]
Let's go with #projects-using-this-api. I'm pretty sure nothing else references it, and if so, it will still point to the same page.

**Comment by cadesalaberry** [comment]
Roger roger.

And done.

**Pull request merged**
