### PR TITLE
Fix logout

### PR DESCRIPTION
**Pull request by qcmaude**
Fixes issue #57 by not calling listen callback unless logged in :+1: :smile:

### CODE REVIEW

**Comment by Schmavery** [comment]
I'm wondering if, instead of `parseAndCheckLogin`, we should wrap every api function in something that checks login in index.

```
apiFuncNames.map(function(v) {
    var fn = require(".src/"+v)(defaultFuncs, api, ctx);
    api[v] = function(){
        if (ctx.loggedIn) fn.call(arguments);
        else throw new Error("Not logged in.");
    }
});
```

**Comment by Schmavery** [comment]
^ @bsansouci When you get a chance, let me know what you think.  The downside is that it doesn't call the callback with the error, the upside is that you don't need to remember to check logged in status in every function and we make fewer unnecessary calls.  We could hack the callback problem by checking if the last argument is a function and calling it with the error ;)

**Comment by bsansouci** [comment]
I like those changes. @schmavery, I actually don't think that is necessary. Any api calls will crash, and most will actually [catch the "not logged in" error](https://github.com/Schmavery/facebook-chat-api/blob/7c8801046c2770280c0e30bda758960d968920f9/utils.js#L363-L381). So I think a simple fix like this is good.

**Comment by qcmaude** [comment]
LETS MERGE THIS :shipit:

**Pull request merged**
