### PR TITLE
sendMessage fix regarding fb api change

### PR DESCRIPTION
**Pull request by cookkkie**
https://github.com/Schmavery/facebook-chat-api/issues/311

### CODE REVIEW

**Comment by kafeijao** [comment]
Hey @cookkkie thanks for the PR, after I implemented it I'm getting this:

Might be I done something wrong... I started getting the 404 error yesterday, and applied your PR, don't know if I needed to do anything else

`ERR! Error in login: TypeError: utils.generateTimestampRelative is not a function
ERR! Error in login:     at Object.sendMessage (/root/PokemonGo/7.0_pokenotify/node_modules/facebook-chat-api/src/sendMessage.js:253:36)
ERR! Error in login:     at callback (/root/PokemonGo/7.0_pokenotify/app.js:248:13)
ERR! Error in login:     at /root/PokemonGo/7.0_pokenotify/node_modules/facebook-chat-api/index.js:406:14
ERR! Error in login:     at tryCatcher (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in login:     at Promise._settlePromiseFromHandler (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/promise.js:507:31)
ERR! Error in login:     at Promise._settlePromiseAt (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/promise.js:581:18)
ERR! Error in login:     at Async._drainQueue (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/async.js:128:12)
ERR! Error in login:     at Async._drainQueues (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in login:     at Immediate.Async.drainQueues (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in login:     at runCallback (timers.js:570:20)
ERR! Error in login:     at tryOnImmediate (timers.js:550:5)
ERR! Error in login:     at processImmediate [as _immediateCallback] (timers.js:529:5)
ERR! Error in login:  TypeError: utils.generateTimestampRelative is not a function
ERR! Error in login:     at Object.sendMessage (/root/PokemonGo/7.0_pokenotify/node_modules/facebook-chat-api/src/sendMessage.js:253:36)
ERR! Error in login:     at callback (/root/PokemonGo/7.0_pokenotify/app.js:248:13)
ERR! Error in login:     at /root/PokemonGo/7.0_pokenotify/node_modules/facebook-chat-api/index.js:406:14
ERR! Error in login:     at tryCatcher (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in login:     at Promise._settlePromiseFromHandler (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/promise.js:507:31)
ERR! Error in login:     at Promise._settlePromiseAt (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/promise.js:581:18)
ERR! Error in login:     at Async._drainQueue (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/async.js:128:12)
ERR! Error in login:     at Async._drainQueues (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in login:     at Immediate.Async.drainQueues (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in login:     at runCallback (timers.js:570:20)
ERR! Error in login:     at tryOnImmediate (timers.js:550:5)
ERR! Error in login:     at processImmediate [as _immediateCallback] (timers.js:529:5)
TypeError: utils.generateTimestampRelative is not a function
    at Object.sendMessage (/root/PokemonGo/7.0_pokenotify/node_modules/facebook-chat-api/src/sendMessage.js:253:36)
    at callback (/root/PokemonGo/7.0_pokenotify/app.js:248:13)
    at /root/PokemonGo/7.0_pokenotify/node_modules/facebook-chat-api/index.js:406:14
    at tryCatcher (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/root/PokemonGo/7.0_pokenotify/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)`

**Comment by stuartd** [comment]
@kafeijao use genTimestampRelative as that's what's in the published version - changed [here](https://github.com/Schmavery/facebook-chat-api/commit/1847747f191c41398b3c8c783c8efbb993763948)

**Comment by kafeijao** [comment]
@stuartd Thanks a lot man! It seems the npm version of this doesn't have the latest commits. It's working again 👍 👍 👍

**Comment by Schmavery** [comment]
Thanks a lot for your changes @cookkkie!  I merged @Mini-Geek's version because it solved a couple more issues and had the results from running the tests.

**Pull request closed without merging**
