### PR TITLE
Made MQTT connect code simpler

### PR DESCRIPTION
**Pull request by ptrcnull**
Removed unused code, eg. detecting protocols or parsing URL just to serialize it later

### CODE REVIEW

**Comment by Hongarc** [comment]
You must remove `require fbconnect`

**Comment by Schmavery** [comment]
Thanks for reviewing, @Hongarc 
@7osCraft since you wrote the original version of this (that's being partially deleted here), do you mind taking a quick look and giving your thoughts?

**Comment by 7osCraft** [comment]
I took a look and everything looks good. That code was only used to get the protocol but it's not needed anymore.

**Comment by Schmavery** [comment]
Thanks everyone

**Pull request merged**
