### PR TITLE
Fix crash on plan creation

### LINKED ISSUE #607: Error when setting an event
```javascript
{ error: 'Problem parsing message object. Please open an issue at https://github.com/Schmavery/facebook-chat-api/issues.',
  detail: TypeError: Cannot read property 'text' of null
    at _formatAttachment (/path/node_modules/facebook-chat-api/utils.js:453:46)
    at attachments.map.v (/path/node_modules/facebook-chat-api/utils.js:502:55)
    at Array.map (<anonymous>)
    at Object.formatDeltaMessage (/path/node_modules/facebook-chat-api/utils.js:502:46)
    at resolveAttachmentUrl (/path/node_modules/facebook-chat-api/src/listen.js:214:38)
    at resolveAttachmentUrl (/path/node_modules/facebook-chat-api/src/listen.js:231:30)
    at parsePackets (/path/node_modules/facebook-chat-api/src/listen.js:234:19)
    at Array.forEach (<anonymous>)
    at /path/node_modules/facebook-chat-api/src/listen.js:133:12
    at tryCatcher (/path/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/path/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/path/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/path/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/path/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/path/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/path/node_modules/bluebird/js/main/async.js:15:14),
  res:
   { ofd_ts: 1520765122540,
     delta:
      { attachments: [Array],
        irisSeqId: '7233',
        messageMetadata: [Object],
        class: 'NewMessage' },
     type: 'delta',
     iseq: 7233,
     queue: 100018572888779 },
  type: 'parse_error' }
```

### PR DESCRIPTION
**Pull request by ravkr**
fixes #607 and #587
can you test it @Bjornskjald ?

### CODE REVIEW

**Comment by Bjornskjald** [comment]
```javascript
{ type: 'message',
  senderID: 'redacted',
  body: '',
  threadID: 'redacted',
  messageID: 'mid.$cAAAAAvyXoN1oTBtcWSiGtYTRnltr',
  attachments:
   [ { type: 'share',
       description: 'Ty i Jan również otrzymacie przypomnienie 1 godz. przed zaplanowanym terminem.',
       ID: '895885673923436',
       subattachments: [],
       width: null,
       height: null,
       image: null,
       playable: null,
       duration: null,
       source: null,
       title: '17 marca o 11:00',
       facebookUrl: null,
       target: [Object],
       styleList: [Array],
       url: null } ],
  mentions: {},
  timestamp: '1520868660225',
  isGroup: false }
```
I think it works

**Comment by ravkr** [comment]
@Schmavery @bsansouci could you merge it?

**Comment by ravkr** [comment]
Yes, it would be possible, but we have to get this eventID: 
obraz

and then submit POST request to `https://www.messenger.com/ajax/eventreminder/?event_reminder_id=1676785955709101&dpr=1`
it would give us:
obraz

maybe I'll add it soon.. but it would be great if someone else could do it 
I don't have much time now

**Comment by ravkr** [comment]
@Schmavery are you there?

**Comment by Schmavery** [comment]
Thanks. Sorry about all the delays @ravkr

**Pull request merged**
