### PR TITLE
Fixed resData.entries error

### PR DESCRIPTION
**Pull request by mjkaufer**
Fixed the following issue, https://github.com/Schmavery/facebook-chat-api/issues/26, by changing references to `resData.entries` to `resData.payload.entries`

### CODE REVIEW

**Comment by bsansouci** [comment]
Thanks for this fix! I feel like it doesn't make much sense for getUserId to return that big object. Maybe it should return `resData.payload.entries` instead, because that's the only thing that really matters. What do you think?

**Comment by mjkaufer** [comment]
Yeah, I think `resData` has a bunch of junk. Really, the only potentially useful info is in payload.

**Comment by bsansouci** [comment]
Ok cool, then if you can make getUserInfo only return `resData.payload.entries` we can merge this PR

**Comment by mjkaufer** [comment]
That said, lots of methods return `resData`, which I don't think have entries objects, so it would make a bit of an inconsistency across methods, so maybe returning `resData` is the best option

**Comment by mjkaufer** [comment]
Let me know, and I'll update the method and fix the README for this stuff and the login feature. 

Also, do we want to read the `config.json` file from the `login` function itself, or should we just call a read function and pass the object to `login`?

**Comment by bsansouci** [comment]
> That said, lots of methods return resData, which I don't think have entries objects, so it would make a bit of an inconsistency across methods, so maybe returning resData is the best option

I don't know which methods you're referring to, but that sounds like it shouldn't be the case. Can you point out to me which ones you're thinking of? I think it makes more sense to avoid exposing FB directly because they don't mean a lot without context. @Schmavery thoughts?

As I said in the other PR, we should talk about the readme stuff over there.

**Comment by mjkaufer** [comment]
I implemented the changes you wanted!

**Comment by bsansouci** [comment]
Cool thanks :)
Will merge once you update sendDirectMessage and sendDirectSticker

**Comment by mjkaufer** [comment]
I'm not sure what I need to do to `sendDirectMessage` and `sendDirectSticker`... they both use payload now, don't they?

**Comment by bsansouci** [comment]
Well `getUserId` already returns `resData.payload.entries`, so instead of `data.payload.entries[0].uid` you're gonna want `data[0].uid`

**Comment by mjkaufer** [comment]
Oh, whoops

**Comment by mjkaufer** [comment]
Everything's up to date. Thanks for the catch!

**Comment by Schmavery** [comment]
One last thing - doesn't the README example for `getUserId()` still refer to `data.payload.entries[0].uid`?

**Comment by mjkaufer** [comment]
Not anymore! :smile:

**Pull request merged**
