### PR TITLE
Add api.sendTypingIndicator

### PR DESCRIPTION
**Pull request by blazeu**
Send typing indicator for other users in the chat to see.

The typing indicator will disappear automatically after 30 seconds or after sending a message (```api.sendMessage```).

However, this can be overridden by sending a request again, with the field ```typ``` being ```0``` instead of ```1```.
Still thinking the best idea to implement this tho.

Any suggestion?

### CODE REVIEW

**Comment by Schmavery** [comment]
Am I correct in understanding that this is in order to send a indication to other users that the api is typing, rather than detecting other users who are typing?

**Comment by blazeu** [comment]
Yes, this is for **sending** typing indicator.

**Comment by Schmavery** [comment]
Maybe we can call it `sendTypingIndicator` and have it call the callback with a function that allows you to end the indicator early (with the `typ` field `0`).

**Comment by bsansouci** [comment]
This looks good, thanks a lot :D

**Pull request merged**
