### PR TITLE
Get access token by app_id

### PR DESCRIPTION
**Pull request by davidyen1124**
Use Graph API Explorer api to get access token.

### CODE REVIEW

**Comment by Schmavery** [comment]
Why is this useful to provide as part of a chat api?  Aren't there already packages dedicated to this?  I'm under the impression that this is exactly what https://github.com/jaredhanson/passport-facebook does.

**Comment by davidyen1124** [comment]
We can use access token to [send page message](https://developers.facebook.com/docs/graph-api/reference/v2.4/page/conversations), I think it can be a feature in your project

**Comment by Schmavery** [comment]
We already support sending messages as a page.  Are you suggesting that this should be implemented differently?

**Comment by davidyen1124** [comment]
Yours is fine. Should I close this PR?

**Comment by Schmavery** [comment]
Might as well.  Thanks for the contributing though, and let us know if you run into any problems with sending messages as a page.  This is a less-often used functionality to it's useful to get feedback. :smile:

**Pull request closed without merging**
