### PR TITLE
Fix response handling with multiple objects (#616)

### PR DESCRIPTION
**Pull request by ravkr**
Just a fix for #616

### CODE REVIEW

**Comment by ravkr** [comment]
@Schmavery could you merge?

**Comment by Schmavery** [comment]
Thanks for doing this, we will merge after we merge the dev branch (hopefully tonight).

**Comment by ravkr** [comment]
I think we can merge it now

**Comment by ravkr** [comment]
@Schmavery ?

**Comment by Schmavery** [comment]
Thanks

**Pull request merged**
