### PR TITLE
Multiple message callbacks for listen (close #525)

### LINKED ISSUE #525: Multiple message callbacks for listen
Hey !
When we use the method `listen`, we can use only one callback.  

To explain, i have this example:
```javascript
api.setOptions({
        listenEvents: true,
        logLevel: "silent"
});
// After...
api.listen((err, message) => {
    console.log("not called");
});
api.listen((err, message) => {
    console.log("called");
});
```  
and the output is:
```  
info login Logging in...
info login Logged in
info login Request to reconnect
info login Request to pull 1
info login Request to pull 2
info login Request to thread_sync
info login Done logging in.
called
called
called
```

I think that's a good idea to add multiple 'listener' of message :)

### PR DESCRIPTION
**Pull request by Vinetos**
Now we can call several times `listen` to use more than one callbacks
Also close #525

### CODE REVIEW

**Comment by QuenK1** [comment]
Is very good idea ! :D

**Comment by Schmavery** [comment]
Hi @Vinetos, thanks for contributing! As I said in #525, I'm not convinced this is necessary -- this functionality can be very easily accomplished in user code.
Is there a use case that I'm missing that is impossible/hard to accomplish without this change?

**Comment by Schmavery** [comment]
See also my example in https://github.com/Schmavery/facebook-chat-api/issues/525#issuecomment-329016053

**Comment by Schmavery** [comment]
Closing as explained in #525, feel free to comment if you have any issues.

**Pull request closed without merging**
