### PR TITLE
Added way to get file attachment

### PR DESCRIPTION
**Pull request by webfreak7**
self explanatory. Pretty much takes care of any file attachments you throw at it. Tried adding photo attachments, but the url returned was super weird and didn't work (something along the lines of /ajax/mercury/attachements...). Will add if I find a way to do it.

### CODE REVIEW

**Comment by blazeu** [comment]
there's ```preview_url```, ```thumbnail_url``` and ```hires_url``` for photo attachments and seems to be working fine if opened.

**Comment by bsansouci** [comment]
When you say "Tried adding photo attachments" you mean upload photos? Because we're working on that, we'll publish soon.

I just tried to send myself a picture and the `type` was `"photo"` and not `"file"`. @blazeu is right, hires_url seems to be the full version. My guess is that if you do a post request (after being logged in) to http://facebook.com/{attachement.url}, you'll get the image.
 
Can make this work for picture too? I'll merge after that :)

**Comment by webfreak7** [comment]
I added in support for photos and gifs.

**Comment by Schmavery** [comment]
Awesome, thanks.

**Pull request merged**
