### PR TITLE
Fixed README error

### PR DESCRIPTION
**Pull request by mjkaufer**
You were passing a string to the login object, when in actuality, you had to pass an actual object. Fixed the error by using `fs` to read from the config file.

### CODE REVIEW

**Comment by bsansouci** [comment]
Good catch! Do you mind fixing all of the logins? I think we use it in most examples. Maybe using env variables because it would be shorter...

**Comment by mjkaufer** [comment]
Sure. I'll probably do a `fs.readFileSync` in the interest of not having the code grow sideways faster than vertically. Alternately, I can implement the file reading in `index.js` so the current documentation is valid. Either way, I'm going to close this, and we can continue discussing here: https://github.com/Schmavery/facebook-chat-api/pull/27

**Comment by bsansouci** [comment]
If you want to fix the Readme, let's keep the discussion here instead of polluting other PRs.
No don't add it in index.js, we removed it because there are too many ways to load that data. It doesn't make sense for us to implement only a few of them nor does it make sense to implement all possible ways, so we just don't implement them.

readFileSync works for me :)

**Comment by mjkaufer** [comment]
Sounds good. I updated the rest of the examples.

**Comment by Schmavery** [comment]
Good catch, we should have read over the README closer after removing that functionality.
I think it's important to keep the examples short and to the point, while still being functional working (copy pasteable) examples.

The filename was used in order to shorten the examples, but relying on a file introduces a black box into the example where it's not immediately clear what data should be in the file.

I think it would be clearer and more concise to provide examples in this form:
```js
login({email: "FB_EMAIL", password: "FB_PASSWORD"}, function callback (err, api) {
    // stuff
});
```

**Comment by mjkaufer** [comment]
Sounds good. I just added that.

**Comment by bsansouci** [comment]
Thanks a lot :+1:

**Comment by mjkaufer** [comment]
No problem

**Pull request merged**
