### PR TITLE
update to improve compatibility with new api

### PR DESCRIPTION
**Pull request by Mini-Geek**
Related to bug #311. Pull request #315 only attempted to fix sendMessage, this includes 3 more services.

Functions updated:

- addUserToGroup
- changeGroupImage
- sendMessage
- setTitle

Changes made:

- Remove `message_batch[0]`
- Change https://www.facebook.com/ajax/mercury/send_messages.php to https://www.facebook.com/messaging/send/

The unit testing currently produces 30 passes and 5 failures for me.

- Login As Page:
  1. should send text message object (user)
  2. should send sticker message object (user)
  3. should send basic string (user)
  4. should get a list of online users
- Login:
  5) should get a list of online users

The errors indicate:
- The URL for getOnlineUsers, https://www.facebook.com/ajax/chat/buddy_list.php, also returns a 404. I haven't been able to find the new URL and/or formatting for this.
- Things in Login As Page that send messages are not sent with an error saying "This person isn't receiving messages from you right now." (this may just be an issue with my test users/pages)

### CODE REVIEW

**Comment by Kurimizumi** [comment]
`changeThreadEmoji()` is also broken, but `changeThreadColour()` is still working.

If I find any other broken functions I'll post them too.

**Comment by Schmavery** [comment]
Thanks, this is awesome.
In the past, sometimes pages use an older version of the service, it seems.  Is there any chance the pages tests pass with no changes?
GetOnlineUsers is a known issue and the api function probably has to be deprecated https://github.com/Schmavery/facebook-chat-api/issues/278

**Comment by Mini-Geek** [comment]
Kurimizumi, changeThreadEmoji is working for me. I'm not sure what problems you're having with it. 

I just checked, my changes didn't break the Login As Page tests. They didn't fix any of them, either: the same 4 tests fail with or without my changes here (again, that's with my test setup, which may be the issue).

**Comment by GAMELASTER** [comment]
I think we need update a readme too for inform others which version to use if some function dont work

**Comment by Schmavery** [comment]
Thanks again @Mini-Geek, I'll push an update to npm when I get home today.

**Comment by Mini-Geek** [comment]
Awesome, glad I could help! Also, I figured out that for a page to message someone, they have to message the page first. So I messaged my page as my test user, and disabled the two "should get a list of online users" tests, and now I get no failures when I run the test.

So it all appears good to me! (or, as good as it can with that known broken API)

**Pull request merged**
