### PR TITLE
Hitting the right server

### PR DESCRIPTION
**Pull request by GAMELASTER**
I investigated how is *-edge-chat generated, if it is a really random or not.
The result, its really random!
For explain I write the process lower, but first to code.
I written generateSubdomain similar to original code for future change (max_conn, or L can be changed). I supposed its a best way, if not, sorry!

So, this is explain:
The function of generating is in ChannelSubdomain (for search in Chrome Debugger, use CTRL SHIFT F for search in Sources tab), the Q function (exported as allocate), with three parameters, only first is used, and its max_conn (search this for executing append).
In allocate (returning a U % L) function is first created an U variable, what I used in my function. Then is used random to get an S, random generated number from U. And N, N has same value as S, all of the time (if code failure, N is set to S). In block with N is something like checking of something with IDs, I really have not idea what it is, but its not doing anything with final version, a random U, and after is set some values for channel pubs from N. So, its random!
image

### CODE REVIEW

**Comment by Schmavery** [comment]
In the browser, is the subdomain different every time you pull, or does it stay the same for a while?
I thought it usually stays the same, but maybe that doesn't matter too much.

One issue I see is that all your values are hardcoded constants.  In fact, your whole generateSubdomain function is roughly equivalent to `Math.floor(Math.random() * 7)`...
Ideally we should be able to get these values from somewhere, unless we can establish that they're also hardcoded in the client, in which case, we might be able to get away with it.

**Comment by Schmavery** [comment]
As far as I'm concerned, a fix for this would also include a strategy for caching the subdomain and retrying with a new subdomain if the call fails.

**Comment by GAMELASTER** [comment]
Subdomain is changed every refresh of website. I Will look if it's not changed more times while a runtime

**Comment by mehcode** [comment]
> Subdomain is changed every refresh of website. 

Yes and no. On a refresh facebook will try to keep you at the same subdomain unless its been more than `100 * 1000` milliseconds since the refresh. 

I did a small bit of investigation myself on this: https://github.com/Schmavery/facebook-chat-api/issues/161

We should probably just implement something that changes the subdomain every so often and re-authorizes there. 

`Math.floor(Math.random() * 7)` is more than enough. 

The facebook client code is just plain weird.

**Comment by GAMELASTER** [comment]
@mehcode, yep, you are right! Yes, FB code is creepy.

**Comment by Schmavery** [comment]
My issue is mainly with hardcoding a '7' into our code empirically.  I'm not saying we don't do that in other places, but it's not ideal.
Not planning on merging this unless `generateSubdomain()` is cleaned up and the caching is addressed.  Thanks for investigating further into that @mehcode.

Honestly, with them picking servers randomly rather than doing any kind of active load-balancing or anything, I feel this is a low priority change that is unlikely to fix anything unless we are able to change servers upon failure of the request.

**Comment by GAMELASTER** [comment]
Well, I can close this pull request.

(omg, sorry for broken things with pull request)

**Pull request closed without merging**
