### PR TITLE
ESLint formatting

### PR DESCRIPTION
**Pull request by ravkr**
I've put some ESLint rules as proposed in #599 and used automated fixing on the code (there are few more things to review by hand), if you think that something would look better in another way, just propose it here

### CODE REVIEW

**Comment by Schmavery** [comment]
Thanks @ravkr, helps to be able to visualize it. Do these eslint rules match one of the standards mentioned in #599?

**Comment by ravkr** [comment]
I didn't check every aspect of these standards
I've just installed eslint and then just put some rules to more of less match current style
eg. object should look like this:
```js
var obj = {
  abc: "hello"
}
```
like lines 121 and 125 here
obraz

IMO neither *standard* nor *airbnb* fits us, but this one is closer to *airbnb*

**Comment by ALiangLiang** [comment]
Maybe we can use standard style. If @Schmavery really like semicolons. We can use [this style](https://github.com/Flet/semistandard) based on standard but use semicolons. It suitable for semicolons fans.

**Comment by ravkr** [comment]
Why not make list with our own rules? Like the one in this commit (with few more of course)

**Comment by ALiangLiang** [comment]
um..... I think this is a big project which contributing by many developers. They have different habit about coding style. So I suggeted use some famous popular coding style is better.

Of course, we need to choose most like us style.

I have some reasons:
1. This project has different style now.
2. ~~Apply popular style is easy 😛~~

**Comment by Schmavery** [comment]
Going to close this because of the prettier changes. Thanks for the feedback!

**Pull request closed without merging**
