### PR TITLE
Removed pull

### LINKED ISSUE #794: HTML Received instead of JSON in pull request.
Trying to login:

```
ERR! login Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.
{ error: 'Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.' }
```

Login code:
```
const obj = {email: "**[REDACTED]**", password: "**[REDACTED]**"};

login(obj, (err, api) => {

    if(err) {

        switch (err.error) {

            case 'login-approval':
    
                console.log('Enter code > ');
    
                rl.on('line', (line) => {
                    err.continue(line);
                    rl.close();
                });

                break;

            default:

                console.error(err);

        }

        return;

    }
```

### PR DESCRIPTION
**Pull request by 7osCraft**
Removed pull because it's not used anymore by Facebook. Fixes #794

### CODE REVIEW

**Comment by KMatuszak** [comment]
Works without any issues for me 🎉

**Comment by Schmavery** [comment]
thanks for doing this and to the people who tested it too :)

**Comment by JosephBBa** [comment]
@KMatuszak @7osCraft @Schmavery 
Hello Everyone,
I hope you all are safe and you are doing well. 
Please can someone give me a screenshot of his workspace about Facebook Chat Api how it works currently because I saw a set of changes include:
-  Removed pull #800 

These are tough times and I wish the best to each one of you. Please do take care of yourself and your families.  
There is nothing more I want to say except wishing you good health and stay strong. Thank you for your continued support :) Cheers!

Regards,

**Comment by 7osCraft** [comment]
Hello @JosephBBa,
  I appreciate your wishes and good words, I hope you are well and safe too.

I don't exactly understand what you mean by a screenshot of our workspace. I'll try to explain to you how the library works.

It emulates accessing Facebook's website from a browser by doing the same http requests that are done by the browser.
This includes logging in and using saved cookies to access the endpoints.
And for listening for incoming messages, Facebook uses MQTT which is a protocol used to send and recieve messages. 
Facebook doesn't have an official api for normal accounts (They have it for page bots only) so that's why this library is here.
That also means if Facebook changes something, then we need to see that change and implement it in facebook-chat-api.

Cheers!

**Comment by JosephBBa** [comment]
Hi @7osCraft,
Thanks for the response. It's me again and I hope you're going well so far.
Would you mind provide any code that I can send a message to user x?
I'll keep an eye out for your response!

Kind regards,

**Comment by KMatuszak** [comment]
@JosephBBa Everything about sending messages is described in the docs here https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#sendMessage

**Pull request merged**
