### PR TITLE
async support

### PR DESCRIPTION
**Pull request by kabirvirji**
Ran into an issue with async functions since `utils.getType(options) === 'Function'` only checks for regular Functions, and `utils.getType(options)` returns `AsyncFunction` for Async Functions.

### CODE REVIEW

**Comment by bsansouci** [comment]
Hey @kabirvirji does the API really work when passed an async function?

**Comment by Schmavery** [comment]
I also can't imagine this is the only place that checks if a callback is `=== 'Function'`?

**Comment by kabirvirji** [comment]
@bsansouci I believe it does, that's how I've been using it

@Schmavery The `=== 'Function'` check happens in 8 places, I can add the `AsyncFunction` check to all of them if you think its a good idea, let me know.

**Comment by bsansouci** [comment]
Great to hear! Yeah let's update them in all 8 places to make sure you don't break again :)

**Comment by kabirvirji** [comment]
@bsansouci @Schmavery Done, let me know if anything needs a tweak.

**Comment by bsansouci** [comment]
It looks good! Thanks a lot.

**Pull request merged**
