### PR TITLE
#390 improve formatThread to not return empty name property

### PR DESCRIPTION
**Pull request by kamdz**
now util function formatThreat return as name property:
-firstly name if it exists, if not then
-custom name of conversation if it set by us, if not then
-other user fbid in one-on-one conversation
-string with coma separated fbids of all users in group conversation

last two options is for example to mapping when we have cached friends list in our map or something like this

### CODE REVIEW

**Comment by Schmavery** [comment]
Why not simply have the name empty in the last two cases and have consumers of the API access those ids from the other fields in the returned thread object?

**Comment by kamdz** [comment]
Ok, I see the point, I changed my pr :)

**Comment by Schmavery** [comment]
Great, thanks for doing this, I think I understand better now.
Can we instead expose a nicknames field like returned by getThreadInfo?  An empty thread name is a valid expected return value.

**Comment by kamdz** [comment]
Ok, no problem. Can I return also other_user_fbid value?

**Comment by kamdz** [comment]
Check it now :) 
btw. great project! thanks

**Comment by Schmavery** [comment]
Isn't other_user_fbid the same id as in participants?
I appreciate you sticking with this, I'll give you some insight into why I have to be a little picky.  t's a little tricky to design this api in way that will stay easy to use.  I already think we expose wayyy too many useless fields on this object so I'm trying to get get even more bloat if we can avoid it.

**Comment by kamdz** [comment]
Yes, it's one of them. For example in single conversation participants contains my fbid and other_user_fbid. Ok, I will change it ;p

**Comment by Schmavery** [comment]
Can we just call it "nicknames" to match getThreadInfo.  Also if you could add a quick change to the docs so that people know this will return the new field that would be awesome.

**Comment by kamdz** [comment]
Done!

**Comment by Schmavery** [comment]
Great thanks!

**Pull request merged**
