### PR TITLE
Attempt to fix redirection to certain Facebook subdomains

### LINKED ISSUE #592: Can't send message
I have tried the echo bot example and it is thrown an error when I send a message to the bot.

The bot didn't reply my message and here is the error.
asd

and the code
qweasd

### PR DESCRIPTION
**Pull request by Toohpick**
Fixes #592 
Please let me know if there is a better way to do this.

### CODE REVIEW

**Comment by Schmavery** [comment]
can anyone without this redirect issue verify that the normal path still works as expected? (@ravkr )

**Comment by bsansouci** [comment]
Hope this works for people having this issue! Thanks for the fix :)

**Comment by ALiangLiang** [comment]
I just tested the old and this version. Both can work. 👍

**Comment by Schmavery** [comment]
Great, thanks @ALiangLiang

**Pull request merged**
