### PR TITLE
change message_reply senderID type to str

### PR DESCRIPTION
**Pull request by andybui01**
senderID for event type - message is a string. For consistency purposes, message_reply's senderID should be a string and not an integer.

### CODE REVIEW

**Comment by andybui01** [comment]
Hmm I'm not sure where else senderID is an integer but it's also an integer for "message_reaction" events. In that case, is message's senderID supposed to be an integer?

**Comment by 7osCraft** [comment]
It should be a string along with threadID in every event.

**Comment by Schmavery** [comment]
Seems ok to me -- @andybui01 can you fix it for message_reaction too? thanks

**Comment by andybui01** [comment]
I took a closer look at some of the events and here are some events with integer IDs. I'm guessing all of these should be strings instead.

**presence**
- userID

**message_reply**
- threadID
- senderID
- messageReply:
- - threadID
- - senderID

**message_reaction**
- threadID
- senderID
- userID

**message_unsend**
- threadID
- senderID

**Comment by Schmavery** [comment]
Hey @andybui01 sorry about the miscommunication and thanks for bringing up this issue. I think some of the issues may have been addressed in the recently-merged #779 but if there's anything missing feel free to make it known.

**Pull request closed without merging**
