### PR TITLE
Added customTagNames to formatThread

### PR DESCRIPTION
**Pull request by matthiashhh**
I need to retrieve the tags of the threads, thus added this to formatThread() in utils.js.

### CODE REVIEW

**Comment by Schmavery** [comment]
Ok we can probably do this, but can you please give more information about what this is?  I'm not aware of tag names for threads.. maybe a feature I didn't hear about?  What format is the data in? If you're going to add this, can you also tweak the docs to reflect it?

**Comment by matthiashhh** [comment]
The tags are called labels in the GUI and documentation:
https://www.facebook.com/help/935707876542654
In a thread object, the following member appears (example):
```
"page_thread_info": {
	"flagged": false,
	"customTagNames": ["My label"]
}
```
[Full example](https://github.com/Schmavery/facebook-chat-api/files/389189/example.json.txt)

**Comment by matthiashhh** [comment]
Added  'customTagNames' to the list of properties in the callback from getThreadList in DOCS.md

**Comment by Schmavery** [comment]
Does this only happen messages sent by pages?  What happens if you're just sending/receiving as a user account?  I would imagine the `page_thread_info` field wouldn't exist in this case, causing `formatThread()` to throw an exception?

**Comment by matthiashhh** [comment]
You are right, the `page_thread_info` field is not there for messages in a user account. Moreover, when there are no `customTagNames`, the value is an empty array:
`"page_thread_info": []`
Is there a way around this? For those who use Facebook Pages, labeling is a very useful feature.

**Comment by Schmavery** [comment]
I think I would be okay with simply only including this field for pages.  If it is a normal user message (i.e. no `page_thread_info` field, simply do not include that field in the returned object? 
@bsansouci let me know what you think of this.

Regarding the second issue, it looks like `page_thread_info` is sometimes an object and sometimes an empty array?  What does the `flagged: false` refer to in the original example?  Could this be something we could either strip out or default to false if unspecified?  Maybe I'm misunderstanding what's going on.

**Comment by matthiashhh** [comment]
Here is a screenshot showing how to flag a thread:
flag
 I assume the `flagged` field refers this. Also you can see the labels (tags) 'Joshua' and 'Voice'.

**Comment by matthiashhh** [comment]
The retrieval of customTagNames now handles undefined page_thread_info objects. In these cases, `customTagNames: undefined` will be returned. The same happens when no labels has been assigned a page thread. Have tested it against user threads, as well as page threads with and without labels.

You might want to take a look at my way of checking for undefined, I'm not a javascript programmer. It works, but for all I know, there could be better ways :)

**Comment by matthiashhh** [comment]
Also, I guess we should give some thought to whether it is best to flatten the structure by adding the page_thread_info children directly to the root, as done in this request, or whether we should maintain the original structure by letting customTagNames (and flagged) be children of a pageThreadInfo object.

**Comment by bsansouci** [comment]
Hey @matthiashhh, can you explain the difference between this PR and the one I just merged https://github.com/Schmavery/facebook-chat-api/pull/308 ?

**Comment by Schmavery** [comment]
I'm going to close this, as it seems like #308 fixed the same issue.  Thanks for much for investigating this @matthiashhh, and please comment if there's anything we missed :)

**Pull request closed without merging**
