### PR TITLE
[WIP] Fix delay at pull 2 & add options to set online state.

### LINKED ISSUE #781: Delay after "Request to pull 2"
When I log in, I get the usual series of logs:

> info login Logged in
> info login Request to reconnect
> info login Request to pull 1
> info login Request to pull 2

Since this morning, however, there's been a delay after this log (about 30 seconds to a minute?) before the final two logs (below) are printed and the login callback is called.

> info login Request to thread_sync
> info login Done logging in.

Is there any reason why thread_sync may have started to hang?

### PR DESCRIPTION
**Pull request by lequanglam**
resolves #781.

### CODE REVIEW

**Comment by AstroCB** [comment]
@Schmavery

**Comment by AstroCB** [comment]
I've been using this change for a bit and everything is looking good on my end

**Comment by lequanglam** [comment]
bump @Schmavery

**Comment by 7osCraft** [comment]
Tested this and everything is working fine. Thanks!

**Comment by lequanglam** [comment]
i'm not quite sure Facebook is using pull anymore.

*pls don't merge yet*

**Comment by Hongarc** [comment]
> i'm not quite sure Facebook is using pull anymore.
> 
> _pls don't merge yet_

You should add [WIP] in title

**Comment by pcr910303** [comment]
@lequanglam I didn't understand the whole fix, but is `deasync` needed? It looks like it will block the main thread; why is it insufficient to just run the code after `deasync` inside the promise closure?

**Comment by lequanglam** [comment]
> @lequanglam I didn't understand the whole fix, but is `deasync` needed? It looks like it will block the main thread; 

it *will not* block the main thread. (wrapped inside setTimeout).

> why is it insufficient to just run the code after `deasync` inside the promise closure?

because the whole things need to be inside a loop.

**Comment by pcr910303** [comment]
@lequanglam As far as I understand, it looks like it will block the thread while waiting for the request to `https://0-edge-chat.facebook.com/pull` to finish - the `deasync.while` is busily waiting for the promise to resolve. (Please correct me if I'm wrong)

> wrapped inside setTimeout

The fact that it is wrapped inside a `setTimeout` doesn't make it not block, since `node` is single threaded. `node` eventually executes the function in the `setTimeout` in the event loop, and any JS code can't execute while `deasync.while` is waiting.

> because the whole things need to be inside a loop.

If I understood the code correctly, looks like it's trying to request `https://0-edge-chat.facebook.com/pull` continuously. I think wrapping up the code inside the for loop into a function, and `setTimeout(0)`-ing the function in the end of the promise block would be sufficient.

So... something like this:

```js
// Instead of this:
for(;;) {
    var done = false;
    get("https://0-edge-chat.facebook.com/pull")
        .then(function () { done = true; });
    deasync.loopWhile(function () { return !done; });
}

// I think this will accomplish what you intended:
let ping = function () {
    get("https://0-edge-chat.facebook.com/pull")
        .then(function () { setTimeout(ping, 0); })
};
```

Thanks!

**Comment by pcr910303** [comment]
I think a patch similar to this would work without the dependency of `deasync`:

```patch
diff --git a/DOCS.md b/DOCS.md
index 9a589c8..e85721a 100644
--- a/DOCS.md
+++ b/DOCS.md
@@ -1626,6 +1626,7 @@ __Arguments__
     - `userAgent`: (Default `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18`) The desired simulated User Agent.
 	- `autoMarkDelivery`: (Default `true`) Will automatically mark new messages as delivered. See [api.markAsDelivered](#markAsDelivered).
 	- `autoMarkRead`: (Default `false`) Will automatically mark new messages as read/seen. See [api.markAsRead](#markAsRead).
+	- `online`: (Default `true`) Set account's online state.
 
 __Example__
 
diff --git a/index.js b/index.js
index 0ad1cd5..94d4369 100644
--- a/index.js
+++ b/index.js
@@ -10,6 +10,9 @@ log.maxRecordSize = defaultLogRecordSize;
 function setOptions(globalOptions, options) {
   Object.keys(options).map(function(key) {
     switch (key) {
+      case 'online':
+        globalOptions.online = options.online;
+        break;
       case 'logLevel':
         log.level = options.logLevel;
         globalOptions.logLevel = options.logLevel;
@@ -394,7 +397,7 @@ function loginHelper(appState, email, password, globalOptions, callback) {
         });
     })
     .then(function(resData) {
-      if (resData.t !== 'lb') throw {error: "Bad response from pull 1"};
+      if (resData.t !== 'lb') throw {error: "Bad response from base pull"};
 
       var form = {
         channel : 'p_' + ctx.userID,
@@ -410,23 +413,35 @@ function loginHelper(appState, email, password, globalOptions, callback) {
         sticky_token: resData.lb_info.sticky,
         sticky_pool: resData.lb_info.pool,
       };
-
-      log.info("login", "Request to pull 2");
-      return utils
-        .get("https://0-edge-chat.facebook.com/pull", ctx.jar, form, globalOptions)
-        .then(utils.saveCookies(ctx.jar));
-    })
-    .then(function() {
-      var form = {
-        'client' : 'mercury',
-        'folders[0]': 'inbox',
-        'last_action_timestamp' : '0'
+      var lastOnlineTime = new Date();
+      var ping = function () {
+        log.info("login", "Request to pull (ping)");
+        utils.get("https://0-edge-chat.facebook.com/pull", ctx.jar, form, globalOptions)
+          .then(utils.saveCookies(ctx.jar))
+          .then(function () { 
+            if (globalOptions.online) {
+              lastOnlineTime = new Date();
+            }
+            form = {
+              channel: 'p_' + ctx.userID,
+              seq: 0,
+              partition: -2,
+              clientid: ctx.clientID,
+              viewer_uid: ctx.userID,
+              uid: ctx.userID,
+              idle: Math.floor((new Date().getTime() - lastOnlineTime.getTime()) / 1000),
+              cap: 8,
+              msgs_recv: 0,
+              sticky_token: resData.lb_info.sticky,
+              sticky_pool: resData.lb_info.pool,
+            };
+            if (globalOptions.online) {
+              form.state = 'active';
+            }
+            setTimeout(ping);
+          });
       };
-      log.info("login", "Request to thread_sync");
-
-      return defaultFuncs
-        .post("https://www.facebook.com/ajax/mercury/thread_sync.php", ctx.jar, form, globalOptions)
-        .then(utils.saveCookies(ctx.jar));
+      setTimeout(ping);
     });
 
   // given a pageID we log in as a page
@@ -471,7 +486,8 @@ function login(loginData, options, callback) {
     autoMarkDelivery: true,
     autoMarkRead: false,
     logRecordSize: defaultLogRecordSize,
-    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18"
+    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18",
+    online: true
   };
 
   setOptions(globalOptions, options);
```

**Comment by lequanglam** [comment]
closing this because look like Facebook is removing pull request.

**Pull request closed without merging**
